---
- hosts: all

  vars:
    pip_install_packages:
      - name: docker

  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.git
      become: true
    - role: geerlingguy.pip

  tasks:
    - import_tasks: tasks/configuration.yml
      tags: ["configuration"]

    - import_tasks: tasks/packages.yml
      tags: ["packages"]

    - import_tasks: tasks/vagrant-setup.yml
      tags: ["applications", "vagrant"]


