---
- name: Download sysbox
  get_url:
    url: "{{sysbox_url_deb}}"
    dest: "{{sysbox_tmp_deb}}"
  tags: ["sysbox"]

- name: Calculate checksum of downloaded sysbox package.
  stat:
    path: "{{sysbox_tmp_deb}}"
    checksum_algorithm: sha256
    get_checksum: yes
  register: result
  tags: ["sysbox"]

- debug:
    msg: "The checksum of the file is {{result.stat.checksum}}"
  tags: ["sysbox"]

- name: Verify checksum of downloaded sysbox package.
  fail:
    msg: "Failure, file is invalid"
  when: result.stat.checksum != sysbox_checksum
  tags: ["sysbox"]

- name: Gather info on running Docker containers
  docker_host_info:
    containers: yes
  register: result
  tags: ["sysbox"]

- name: Stop and remove all running Docker containers
  docker_container:
    name: "{{item}}"
    state: absent
  loop: "{{result.containers}}"
  when: result.containers | length != 0
  tags: ["sysbox"]

- name: Install sysbox runtime package
  apt:
    deb: "{{sysbox_tmp_deb}}"
  become: yes
  tags: ["sysbox"]
