---
- name: Download vagrant
  ansible.builtin.get_url:
    url: "{{ vagrant_url_deb }}"
    dest: "{{ vagrant_tmp_deb }}"

- name: Install vagrant for Debian OS family
  ansible.builtin.apt:
    deb: "{{ vagrant_tmp_deb }}"
  become: true

