---
- name: Ensure temp download directory exist.
  file:
    state: directory
    path: "{{ vagrant_tmp_dir }}"

- include: vagrant-debian.yml
  when: ansible_os_family == 'Debian'

- include: vagrant-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure VAGRANT_WSL_ENABLE_WINDOWS_ACCESS is set.
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
    state: present
  loop:
    - export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
