---
- name: Download vagrant
  ansible.builtin.get_url:
    url: "{{ vagrant_url_rpm }}"
    dest: "{{ vagrant_tmp_rpm }}"

- name: Install vagrant for RedHat OS family
  ansible.builtin.yum:
    name: "{{ vagrant_tmp_rpm }}"
  become: true
