---
- name: Ensure temp download directory exist.
  ansible.builtin.file:
    state: directory
    path: "{{ vagrant_tmp_dir }}"

- include: vagrant-debian.yml
  when: ansible_os_family == 'Debian'

- include: vagrant-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Enable Windows access for Vagrant.
  ansible.builtin.lineinfile:
    dest: ~/.profile
    line: "{{ item }}"
    state: present
  loop:
    - export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
    - export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"
